[weeghman]
use_template = base
recursive = yes
process_children_only = yes

[weeghman/media]
process_children_only = yes

[weeghman/backup]
use_template = base
recursive = yes
process_children_only = yes
autosnap = no

[wrigley]
use_template = base
recursive = yes
process_children_only = yes

[template_base]
frequently = 0
hourly = 0
daily = 7
monthly = 3
yearly = 0
autosnap = yes
autoprune = yes
